apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJtZGh1c3NhaW4yODQiLCJwYXNzd29yZCI6Ikh1c3NhaW5AMjg0NCIsImVtYWlsIjoiaHVzc2FpbkBleWVzb25jbG9CJhdXRoIjoiYldSb2RYTnpZV2x1jM05oYVc1QU1qZzBOQT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
